CREATE DATABASE FIRST
CREATE DATABASE USEDB

USE FIRST
GO
CREATE TRIGGER INSERT_TO_USERINFO
ON users
AFTER INSERT
AS
BEGIN
SET NOCOUNT ON
INSERT INTO USEDB.dbo.user_info(login)
    SELECT TOP 1 login FROM users ORDER BY id DESC
PRINT GETDATE()
END
GO

INSERT INTO FIRST.dbo.users VALUES('asd', 'asd')   
SELECT * FROM FIRST.dbo.users
SELECT * FROM USEDB.dbo.user_info